name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-spell-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository 
      uses: actions/checkout@v3
    - name: Spell check README file
      uses: ./
